import { useCallback } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Circle, ClipboardList, MessageCircle, TriangleAlert } from "lucide-react";
import { PatientStatusBadge } from "@/components/patient-portal/PatientStatusBadge";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { Button } from "@/components/ui/button";
import { getPortalCarePlan } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";

function dateOnly(value?: string): string { if (!value) return "Not listed"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(date); }

export function PortalCarePlanPage() {
  const loader = useCallback(() => getPortalCarePlan(), []);
  const { data, loading, error, retry } = usePortalData(loader);
  if (loading) return <PortalLoadingState />;
  if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  return <div><PortalPageHeader title="My Care Plan" subtitle="See the COPD follow-up, home-health, and referral steps your care team has documented." icon={ClipboardList} /><PortalIncompleteData status={data.dataStatus} />
    {data.pathways.length === 0 ? <PortalEmptyState title="No COPD care-plan action is currently listed." detail="Waypoint only shows referrals and follow-up steps that are actually documented in your record. Missing information is not treated as a care gap." /> : <section className="space-y-4" aria-label="Care plan pathways">{data.pathways.map(pathway => <article key={pathway.id} className="rounded-lg border border-[var(--border)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[color:var(--foreground)]">{pathway.title}</h2><p className="mt-1 text-sm text-[color:var(--muted-foreground)]">{pathway.purpose}</p></div><PatientStatusBadge label={pathway.statusLabel} /></div><dl className="mt-5 grid gap-4 border-y border-[var(--border)] py-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Next step</dt><dd className="mt-1 text-sm font-medium">{pathway.nextStep}</dd></div><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Responsible</dt><dd className="mt-1 text-sm font-medium">{pathway.responsibleParty}</dd></div><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Due date</dt><dd className="mt-1 text-sm font-medium">{dateOnly(pathway.dueDate)}</dd></div><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Destination</dt><dd className="mt-1 text-sm font-medium">{pathway.destination ?? "Not listed"}</dd></div></dl>{pathway.patientAction && <p className="mt-4 rounded-lg bg-[var(--info-bg)] p-3 text-sm text-[color:var(--link)]"><strong>Your action:</strong> {pathway.patientAction}</p>}<h3 className="mt-4 text-sm font-semibold">Progress</h3><ul className="mt-2 grid gap-2 sm:grid-cols-2">{pathway.milestones.map(item => <li key={item.label} className="flex items-center gap-2 text-sm text-[color:var(--muted-foreground)]">{item.completed ? <CheckCircle2 className="size-4 shrink-0 text-[color:var(--success)]" aria-hidden="true" /> : <Circle className="size-4 shrink-0 text-[color:var(--muted-foreground)]" aria-hidden="true" />}{item.label}</li>)}</ul>{pathway.barriers.length > 0 && <div className="mt-4 rounded-lg border border-[var(--yellow)] bg-[var(--warning-bg)] p-3"><p className="flex items-center gap-2 text-sm font-semibold text-[color:var(--warning-text)]"><TriangleAlert className="size-4" aria-hidden="true" />Current delays or missing items</p><ul className="mt-2 list-disc pl-5 text-sm text-[color:var(--warning-text)]">{pathway.barriers.map(item => <li key={item}>{item}</li>)}</ul></div>}<Button asChild variant="outline" className="mt-4 min-h-11"><Link to="/portal/messages"><MessageCircle aria-hidden="true" />Ask for help</Link></Button></article>)}</section>}<div className="mt-5"><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div></div>;
}
