import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { HomeHealthVisitNarrative, type HomeHealthCandidate } from "@/components/HomeHealthVisitNarrative";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getPatient, getPatientEncounters, getPatientMedicationRequests, getPatientObservations, getPatientQuestionnaireResponses, getPatientTasks, saveQuestionnaireResponse } from "@/lib/fhir";
import { formatPatientName } from "@/lib/formatters";

const COPD_QUESTIONNAIRE = "https://waypoint.example/fhir/Questionnaire/copd-home-health-subset";
const COPD_FIELDS = [["spo2", "SpO2"], ["respiratory-rate", "Respiratory rate"], ["mmrc", "mMRC dyspnea"], ["dyspnea-activity", "Dyspnea with activity"], ["oxygen-use", "Oxygen use"], ["oxygen-flow", "Oxygen flow rate"], ["breathing-baseline", "Breathing compared with baseline"], ["rescue-inhaler", "Rescue inhaler use"], ["medication-use", "Medication use"], ["functional", "Functional activity tolerance"], ["pulmonology", "Pulmonology follow-up"], ["rehab", "Pulmonary rehabilitation"], ["inhaler-technique", "Inhaler technique"], ["smoking-status", "Smoking status"]] as const;
type Answers = Record<string, string>;
function responseAnswers(response: fhir4.QuestionnaireResponse | null): Answers { return Object.fromEntries((response?.item ?? []).flatMap(item => item.answer?.[0]?.valueString !== undefined ? [[item.linkId, item.answer[0].valueString]] : [])); }
function answerItems(answers: Answers) { return COPD_FIELDS.map(([linkId, text]) => ({ linkId, text, answer: answers[linkId] ? [{ valueString: answers[linkId] }] : [] })); }

export function HomeHealthVisitPage() {
  const { visitId } = useParams<{ visitId: string }>();
  const [patient, setPatient] = useState<fhir4.Patient | null>(null); const [observations, setObservations] = useState<fhir4.Observation[]>([]); const [medications, setMedications] = useState<fhir4.MedicationRequest[]>([]); const [tasks, setTasks] = useState<fhir4.Task[]>([]); const [copdResponse, setCopdResponse] = useState<fhir4.QuestionnaireResponse | null>(null); const [oasisResponse, setOasisResponse] = useState<fhir4.QuestionnaireResponse | null>(null); const [copdAnswers, setCopdAnswers] = useState<Answers>({}); const [transcript, setTranscript] = useState(""); const [findings, setFindings] = useState<HomeHealthCandidate[]>([]); const [recording, setRecording] = useState(false); const [dictating, setDictating] = useState(false); const [transcribing, setTranscribing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [liveTranscript, setLiveTranscript] = useState(""); const [interimTranscript, setInterimTranscript] = useState(""); const [liveTranscriptionSupported, setLiveTranscriptionSupported] = useState(true); const [liveTranscriptionError, setLiveTranscriptionError] = useState<string | null>(null); const [encounterId, setEncounterId] = useState<string | undefined>(undefined);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const audioBlob = useRef<Blob | null>(null); const audioStream = useRef<MediaStream | null>(null); const realtimeRef = useRef<RTCPeerConnection | null>(null); const realtimeTextRef = useRef(""); const dictatingRef = useRef(false);

  useEffect(() => { if (!visitId) return; Promise.all([getPatient(visitId), getPatientObservations(visitId), getPatientMedicationRequests(visitId), getPatientTasks(visitId), getPatientQuestionnaireResponses(visitId), getPatientEncounters(visitId).catch(() => [])]).then(([nextPatient, nextObservations, nextMedications, nextTasks, responses, encounters]) => { setPatient(nextPatient); setObservations(nextObservations); setMedications(nextMedications); setTasks(nextTasks); const copd = responses.find(item => item.questionnaire?.includes("copd-home-health-subset")) ?? null; setCopdResponse(copd); setOasisResponse(responses.find(item => item.questionnaire?.includes("oasis-e2")) ?? null); setCopdAnswers(responseAnswers(copd)); setEncounterId(encounters.filter(item => item.class?.code === "HH" && item.status === "finished").sort((a, b) => (a.period?.end ?? "").localeCompare(b.period?.end ?? "")).pop()?.id); }).catch(() => setError("Unable to load this visit.")); }, [visitId]);
  function stopRealtime() { realtimeRef.current?.getSenders().forEach(sender => sender.track?.stop()); realtimeRef.current?.close(); realtimeRef.current = null; setInterimTranscript(""); }
  async function startRealtime(stream: MediaStream) {
    if (!visitId) return;
    realtimeTextRef.current = ""; setLiveTranscript(""); setInterimTranscript(""); setLiveTranscriptionError(null); setLiveTranscriptionSupported(true);
    try {
      const pc = new RTCPeerConnection(); realtimeRef.current = pc; stream.getTracks().forEach(track => pc.addTrack(track, stream));
      const channel = pc.createDataChannel("oai-events");
      channel.onmessage = event => { try { const message = JSON.parse(event.data as string); if (message.type === "conversation.item.input_audio_transcription.delta" || message.type === "response.audio_transcript.delta") { realtimeTextRef.current += message.delta ?? ""; setLiveTranscript(realtimeTextRef.current); if (dictatingRef.current) setTranscript(realtimeTextRef.current); } if (message.type === "error") setLiveTranscriptionError(message.error?.message ?? "OpenAI Realtime transcription error."); } catch {} };
      pc.onconnectionstatechange = () => { if (["failed", "closed", "disconnected"].includes(pc.connectionState)) setLiveTranscriptionError("OpenAI Realtime transcription disconnected. The visit is still being recorded and will be transcribed after recording stops."); };
      const offer = await pc.createOffer(); await pc.setLocalDescription(offer);
      const response = await fetch(`/api/home-health/visits/${encodeURIComponent(visitId)}/realtime`, { method: "POST", headers: { "Content-Type": "application/sdp" }, body: offer.sdp });
      const answer = await response.text(); if (!response.ok) throw new Error(answer || "OpenAI Realtime session could not start.");
      await pc.setRemoteDescription({ type: "answer", sdp: answer });
    } catch (err) { setLiveTranscriptionSupported(false); setLiveTranscriptionError(err instanceof Error ? err.message : "OpenAI Realtime transcription could not start."); realtimeRef.current?.close(); realtimeRef.current = null; }
  }
  function setAnswer(linkId: string, value: string) { setCopdAnswers(current => ({ ...current, [linkId]: value })); }
  // The route parameter is a patient id, so an encounter reference is only written when a real home-health Encounter exists.
  async function saveAssessment(status: fhir4.QuestionnaireResponse["status"] = "in-progress", answers = copdAnswers) { if (!visitId) return; setSaving(true); setError(null); try { const encounter = encounterId ? { reference: `Encounter/${encounterId}` } : copdResponse?.encounter; const next = await saveQuestionnaireResponse({ resourceType: "QuestionnaireResponse", status, subject: { reference: `Patient/${visitId}` }, ...(encounter ? { encounter } : {}), authored: new Date().toISOString(), author: { display: "Waypoint Home Health RN" }, id: copdResponse?.id, questionnaire: COPD_QUESTIONNAIRE, item: answerItems(answers) }); setCopdResponse(next); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save COPD assessment."); } finally { setSaving(false); } }
  function loadDemoTranscript() { setTranscript("Nurse: Tell me what has changed since your COPD hospitalization.\nPatient: My breathing is worse since discharge. I get short of breath walking to the kitchen and stairs are difficult.\nNurse: Are you using oxygen at home?\nPatient: Yes, two liters at night.\nNurse: Are you taking your maintenance inhaler every day?\nPatient: No. I ran out of tiotropium about a week ago. My daughter usually picks up medications, but she is unavailable this week and I cannot afford a refill.\nNurse: Any follow-up arranged?\nPatient: Pulmonology has not been scheduled yet."); }
  async function transcribeBlob(blob: Blob) { if (!visitId) return; setTranscribing(true); setError(null); try { const form = new FormData(); form.append("audio", blob, `${visitId}.webm`); const response = await fetch(`/api/home-health/visits/${encodeURIComponent(visitId)}/transcribe`, { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Transcription failed."); setTranscript(body.transcript ?? ""); setLiveTranscript(body.transcript ?? ""); setInterimTranscript(""); } catch (err) { setError(err instanceof Error ? err.message : "Transcription failed."); } finally { setTranscribing(false); } }
  function startRecording() { setError(null); dictatingRef.current = false; if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined" || typeof RTCPeerConnection === "undefined") return setError("This browser cannot record or connect to live transcription."); navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => { audioStream.current = stream; chunks.current = []; const next = new MediaRecorder(stream); recorder.current = next; next.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data); }; next.onstop = async () => { stream.getTracks().forEach(track => track.stop()); audioStream.current = null; const blob = new Blob(chunks.current, { type: next.mimeType || "audio/webm" }); audioBlob.current = blob; setRecording(false); stopRealtime(); await transcribeBlob(blob); }; next.start(); setRecording(true); void startRealtime(stream); }).catch(() => setError("Microphone permission was denied or no microphone is available.")); }
  function stopRecording() { recorder.current?.stop(); }
  function startDictation() { if (typeof RTCPeerConnection === "undefined") return setLiveTranscriptionError("This browser cannot connect to OpenAI Realtime transcription."); navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => { audioStream.current = stream; dictatingRef.current = true; setDictating(true); void startRealtime(stream); }).catch(() => setLiveTranscriptionError("Microphone permission was denied or no microphone is available.")); }
  function stopDictation() { dictatingRef.current = false; stopRealtime(); audioStream.current?.getTracks().forEach(track => track.stop()); audioStream.current = null; setDictating(false); setTranscript(realtimeTextRef.current); }
  useEffect(() => () => { stopRealtime(); audioStream.current?.getTracks().forEach(track => track.stop()); }, []);
  async function extractFindings() { if (!visitId || !transcript.trim()) return; try { const response = await fetch(`/api/home-health/visits/${encodeURIComponent(visitId)}/extract`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Extraction failed."); const raw = body.findings?.findings ?? body.findings; setFindings(Array.isArray(raw) ? raw : []); } catch (err) { setError(err instanceof Error ? err.message : "Structured extraction failed."); } }
  async function confirmCandidate(candidate: HomeHealthCandidate, editedValue?: string) { if (!visitId || candidate.targetQuestionnaire === "oasis") return; const value = editedValue ?? String(candidate.candidateValue ?? candidate.finding ?? ""); const lower = `${candidate.linkId ?? ""} ${candidate.label ?? ""} ${candidate.finding ?? ""}`.toLowerCase();
    // Increased rescue use is a symptom answer, not an assertion that a medication is not being taken.
    const increasedRescueUse = /rescue|albuterol|salbutamol/.test(lower) && /increas|more often|more frequent|higher/.test(lower);
    if (increasedRescueUse) { const nextAnswers = { ...copdAnswers, "rescue-inhaler": /increas/i.test(value) ? value : "Increased" }; setCopdAnswers(nextAnswers); await saveAssessment("in-progress", nextAnswers); setFindings(current => current.map(item => item === candidate ? { ...item, candidateValue: nextAnswers["rescue-inhaler"], reviewStatus: "confirmed" } : item)); return; }
    const kind = lower.includes("spo2") || lower.includes("oxygen saturation") ? "spo2" : lower.includes("respiratory-rate") || lower.includes("respiratory rate") ? "respiratory-rate" : lower.includes("medication") || lower.includes("inhaler") || lower.includes("refill") || lower.includes("not taking") ? "medication-not-taking" : null; if (!kind) return setError("This candidate needs clinical review in Notes & Coding before it can be written to FHIR."); try { const response = await fetch(`/api/home-health/visits/${encodeURIComponent(visitId)}/confirm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ patientId: visitId, kind, value, medicationRequestId: medications[0]?.id, evidenceText: candidate.evidenceText, reason: candidate.label ?? candidate.finding }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to confirm finding."); const nextAnswers = { ...copdAnswers, ...(candidate.linkId ? { [candidate.linkId]: value } : {}) }; setCopdAnswers(nextAnswers); await saveAssessment("in-progress", nextAnswers); setFindings(current => current.map(item => item === candidate ? { ...item, candidateValue: value, reviewStatus: "confirmed" } : item)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to confirm finding."); } }
  function rejectCandidate(candidate: HomeHealthCandidate) { setFindings(current => current.map(item => item === candidate ? { ...item, reviewStatus: "rejected" } : item)); }
  if (!patient) return <AppShell title="Home Health Visit"><p className="text-sm text-[color:var(--muted-foreground)]">{error ?? "Loading visit..."}</p></AppShell>;
  return <AppShell title="Home Health Visit" subtitle="One visit conversation, reviewed narrative, structured findings, and OASIS evidence"><div className="space-y-5"><Card className="shadow-none"><CardHeader><CardTitle>{formatPatientName(patient)} · Visit workflow</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2 text-sm"><Badge variant={copdResponse?.status === "completed" ? "success" : "warning"}>COPD Assessment: {copdResponse?.status ?? "not started"}</Badge><Badge variant={oasisResponse?.status === "completed" ? "success" : "neutral"}>OASIS-E2: {oasisResponse?.status ?? "not started"}</Badge><Badge variant={tasks.length ? "warning" : "success"}>Open tasks: {tasks.filter(task => task.status !== "completed").length}</Badge><Button asChild variant="outline"><Link to={`/nurse/assessments/${visitId}/oasis`}>Open OASIS-E2</Link></Button></CardContent></Card><HomeHealthVisitNarrative patientId={visitId!} encounterId={visitId} transcript={transcript} onTranscriptChange={setTranscript} onLoadDemo={loadDemoTranscript} onStartRecording={startRecording} onStopRecording={stopRecording} onStartDictation={startDictation} onStopDictation={stopDictation} onTranscribe={() => audioBlob.current ? void transcribeBlob(audioBlob.current) : setError("Record a visit before requesting final transcription.")} recording={recording} dictating={dictating} transcribing={transcribing} liveTranscript={liveTranscript} interimTranscript={interimTranscript} liveTranscriptionSupported={true} liveTranscriptionError={liveTranscriptionError} findings={findings} onConfirmCandidate={confirmCandidate} onRejectCandidate={rejectCandidate} /><Card className="shadow-none"><CardHeader><CardTitle>Waypoint COPD Home Health Assessment</CardTitle><p className="text-sm text-[color:var(--muted-foreground)]">Structured findings are candidates until the nurse confirms them.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{COPD_FIELDS.map(([linkId, label]) => <label key={linkId} className="text-sm"><span className="text-[color:var(--muted-foreground)]">{label}</span><input value={copdAnswers[linkId] ?? ""} onChange={event => setAnswer(linkId, event.target.value)} className="mt-1 h-9 w-full rounded-md border border-[var(--border)] px-2" /></label>)}<div className="sm:col-span-2"><Button onClick={() => saveAssessment()} disabled={saving}>{saving ? "Saving..." : "Save Draft"}</Button><Button className="ml-2" onClick={() => saveAssessment("completed")} disabled={saving}>Complete Assessment</Button></div></CardContent></Card>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex flex-wrap gap-2 text-sm text-[color:var(--muted-foreground)]"><span>Observations: {observations.length}</span><span>Medications: {medications.length}</span><span>OASIS remains a separate CMS-defined assessment.</span></div></div></AppShell>;
}
