import { serve } from "bun";
import index from "./index.html";
import { handleRequest } from "./server/router";

const isProduction = process.env.NODE_ENV === "production";
const port = Number.parseInt(process.env.PORT ?? "3000", 10);

if (!Number.isInteger(port) || port < 1 || port > 65535) {
  throw new Error("PORT must be an integer between 1 and 65535");
}

function isBackendPath(pathname: string): boolean {
  return pathname === "/fhir" || pathname.startsWith("/fhir/")
    || pathname === "/api" || pathname.startsWith("/api/")
    || pathname === "/launch"
    || pathname === "/cds-services" || pathname.startsWith("/cds-services/");
}

async function serveProductionRequest(request: Request): Promise<Response> {
  const { pathname } = new URL(request.url);
  if (isBackendPath(pathname)) return handleRequest(request);

  const relativePath = pathname === "/" ? "index.html" : pathname.slice(1);
  const asset = Bun.file(new URL(`../dist/${relativePath}`, import.meta.url));
  if (await asset.exists()) return new Response(asset);

  // React Router owns client-side paths; unknown asset paths receive the SPA shell.
  return new Response(Bun.file(new URL("../dist/index.html", import.meta.url)));
}

// Development uses Bun's HTML import and HMR. Production serves the files
// generated by `bun run build` while keeping all backend dispatch in router.ts.
const server = isProduction
  ? serve({ port, fetch: serveProductionRequest })
  : serve({
      port,
      routes: {
        "/launch": handleRequest,
        "/fhir/*": handleRequest,
        "/api/*": handleRequest,
        "/cds-services": handleRequest,
        "/cds-services/*": handleRequest,
        "/*": index,
      },
      development: {
        hmr: true,
        console: true,
      },
    });

console.log(`🚀 Server running at ${server.url}`);
